# This workflow updates the `nz-covid19-data` submodule to the latest commit
name: 'Update nz-covid19-data'
on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:
  repository_dispatch:
    types: [update-data]

jobs:
  updatedata:
    name: 'Update nz-covid19-data'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Update references
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit update
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
